---
- name: chronyパッケージ更新と、leapsecmodeをslewに変更
  hosts: all
  become: yes
  become_user: root
  tasks:

  - name: chronydサービスの停止
    service: name=chronyd state=stopped
    
  - name: chronyパッケージの更新
    yum: name=chrony state=latest

  - name: /etc/chrony.confへleapsecmode slew設定を追加
    lineinfile:
      dest: /etc/chrony.conf
      regexp: '^leapsecmode.*$'
      line: 'leapsecmode slew'

  - name: chronydサービスのリスタート
    service: name=chronyd state=started
