---
- name: fetch test
  hosts: all
  become: yes
  become_user: root
  vars:
    - fetch_src: /etc/hosts
    - fetch_dest: /var/tmp
  tasks:

  - name: fetch /etc/hosts from remote host
    fetch:
      src: '{{fetch_src}}'
      dest: '{{fetch_dest}}'
