---
- name: ntpパッケージを更新し、起動時の-xオプション追加
  hosts: all
  become: yes
  become_user: root
  tasks:

  - name: ntpdサービスの停止
    service: name=ntpd state=stopped
    
  - name: ntpパッケージのアップデート(for xleap.patch)
    yum: name=ntp state=latest

  - name: カーネルのステータスリセット(ntptime -s 0 -f 0)
    command: /usr/sbin/ntptime -s 0 -f 0

  - name: /etc/sysconfig/ntpd への -x オプション追加
    replace:
      dest: /etc/sysconfig/ntpd
      regexp: '^OPTIONS.*$'
      replace: 'OPTIONS="-u ntp:ntp -p /var/run/ntpd.pid -g -x"'

  - name: ntpdリスタート
    service: name=ntpd state=started
