---
- name: restart ntp ensuring -x option
  hosts: all
  become: yes
  become_user: root
  tasks:

  - name: set -x option /etc/sysconfig/ntpd
    replace:
      dest: /etc/sysconfig/ntpd
      regexp: '^OPTIONS.*$'
      replace: 'OPTIONS="-u ntp:ntp -p /var/run/ntpd.pid -g -x"'

  - name: restart ntpd
    service: name=ntpd state=started
