---
- name: Satellite 6 (alpha.osaka.redhat.com)のRed_Hat_Japan_Westへ登録
  hosts: all
  vars:
    - satellite: alpha.osaka.redhat.com
    - org: Red_Hat_Japan_West
    - activationkey: RHEL7-library
    
  become: yes
  become_user: root
  tasks:

  - name: Satellite登録のための基本パッケージ追加
    yum:
      name: "http://{{satellite}}/pub/katello-ca-consumer-latest.noarch.rpm"
      state: present
      validate_certs: no
      
#    shell: yum -y --nogpgcheck localinstall http://{{satellite}}/pub/katello-ca-consumer-latest.noarch.rpm

  - name: Satelliteへの登録
    redhat_subscription:
      org_id: '{{org}}'
      activationkey: '{{activationkey}}'

#  - name: Satellite6用toolリポジトリの有効化
#    shell: subscription-manager repos --enable=rhel-7-server-satellite-tools-6.3-rpms

  - name: Satelliteエージェントの導入
    yum: name=katello-agent state=latest

  - name: Satelliteが利用するsshキーの登録
    authorized_key:
      user: root
      state: present
      key: https://{{satellite}}:9090/ssh/pubkey
#      key: '{{ item }}'
#    with_file:
#      - id_rsa_foreman_proxy.pub

