---
- name: 仮想マシンの状態をsnapshot取得時の状態に戻す
  hosts: all
  vars:
    snap_name: 20180522

  become: yes
  become_user: root
  connection: local

  tasks:
    - name: 仮想マシンがシャットダウンされていることを確認
      virt: name={{ inventory_hostname }} state=shutdown
      delegate_to: master
      register: result
      failed_when: result.changed == true

    - name: スナップショットからの復元処理
      command: /usr/bin/qemu-img snapshot -a {{ snap_name }} /images/qemu/{{ inventory_hostname }}.qcow2
      delegate_to: master
