---
- name: 仮想マシンの開始
  hosts: all
  vars:
    guests:
      - RHEL7x
      - RHEL7y
      - RHEL7z

  become: yes
  become_user: root

  tasks:

  - name: 仮想マシン用ネットワーク(default)の開始
    virt_net: name=default state=active

  - name: 仮想マシンの起動
    virt: name={{ item }} state=running
    with_items: "{{ guests }}"
