---
- name: 仮想マシンの停止
  hosts: all
  vars:
    guests:
      - RHEL7x
      - RHEL7y
      - RHEL7z

  become: yes
  become_user: root

  tasks:

  - name: 仮想マシンを停止
    virt: name={{ item }} state=shutdown
    with_items: "{{ guests }}"

  - name: 20秒待ち..
    command: sleep 20

  - name: 仮想マシンの停止を確認
    virt: name={{ item }} state=shutdown
    with_items: "{{ guests }}"
    register: result
    failed_when: result.changed == true
