---
- name: 仮想マシンスタート
  hosts: all
  connection: local

#  become: yes
#  become_user: root

  tasks:

  - name: 仮想マシン用ネットワーク(default)の起動確認
    virt_net: name=default state=active
    delegate_to: 192.168.122.1

  - name: 仮想マシンの起動
    virt: name={{ inventory_hostname }} state=running
    delegate_to: 192.168.122.1
