---
- name: 仮想マシンを初期状態に戻す
  hosts: all
  vars:
    snap_name: init
    guests:
      - RHEL7x
      - RHEL7y
      - RHEL7z

  become: yes
  become_user: root

  tasks:

  - name: 仮想マシンのシャットダウンを確認
    virt: name={{ item }} state=shutdown
    with_items: "{{ guests }}"
    register: result
    failed_when: result.changed == true

  - name: 仮想マシンイメージをsnapshotから戻す
    command: /usr/bin/qemu-img snapshot -a {{ snap_name }} /images/qemu/{{ item }}.qcow2
    with_items: "{{ guests }}"

